[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bpreg"
version = "1.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.7"
authors = [
  { name = "Division of Medical Image Computing, German Cancer Research Center", email = "mic-office@dkfz.de" }
]
maintainers = [
  { email = "s.schuhegger@dkfz-heidelberg.de" }
]
dependencies = [
    "pytorch_lightning==2.2.0",
    "nibabel==5.3.0",
    "scipy==1.16.0",
    "albumentations==1.4.1",
    "dataclasses",
    "numpy==2.2.6",
    "pandas==2.2.2",
    "torch==2.3.0",
    "torchvision==0.18.0",
    "requests==2.32.3",
    "pynrrd==1.1.1",
    "matplotlib"
]

[project.urls]
Homepage = "https://github.com/MIC-DKFZ/BodyPartRegression"

[project.scripts]
bpreg_predict = "bpreg.scripts.bpreg_inference:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
